runtime: php55
api_version: 1
service: default

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /js
  static_dir: js

#- url: /includes
#  static_dir: includes
# application_readable: true

#  retentions db search
- url: /searchresults
  script: /searchresults.html

- url: /resultsblock
  script: /resultsblock.php

- url: /about
  script: /about.html

# TESTING regular retention db search
- url: /testing/
  script: /testing/index.html

- url: /testing/stats
  script: /testing/stats.html

- url: /testing/about
  script: /testing/about.html

- url: /testing/searchresults
  script: /testing/searchresults.html

- url: /testing/resultsblock
  script: /testing/resultsblock.php
  
- url: /testing/resultsblockN
  script: /testing/resultsblockN.php

# TESTING HOLDINGS
- url: /testing/oclc
  script: /testing/holdings/holdings.html

- url: /testing/holdings/searchresults
  script: /testing/holdings/searchresults.html

- url: /testing/holdings/getOCLCHoldings
  script: /testing/holdings/getOCLCHoldings.php

- url: /testing/holdings/getEASTHoldings
  script: /testing/holdings/api.php

- url: /api
  script: /testing/holdings/api.php

- url: /revoked
  script: /testing/holdings/revoked.php

- url: /testing/holdings/getHathiHoldings
  script: /testing/holdings/getHathiHoldings.php

- url: /testing/holdings/getIAHoldings
  script: /testing/holdings/getIAHoldings.php

- url: /testing/holdings/getMemberSpreadsheet
  script: /testing/holdings/getMemberSpreadsheet.php

- url: /testing/holdings/getMemberSpreadsheetDist
  script: /testing/holdings/getMemberSpreadsheet.dist.php

- url: /testing/holdings/getMemberSpreadsheetLive
  script: /testing/holdings/getMemberSpreadsheet.live.php

# HOLDINGS
- url: /oclc
  script: /holdings/holdings.html

- url: /holdings/searchresults
  script: /holdings/searchresults.html

- url: /holdings/getOCLCHoldings
  script: /holdings/getOCLCHoldings.php

- url: /holdings/getRawOCLCHoldings
  script: /holdings/getRawOCLCHoldings.php

- url: /holdings/getEASTHoldings
  script: /holdings/api.php

- url: /api
  script: /holdings/api.php

- url: /revoked
  script: /holdings/revoked.php

- url: /holdings/getHathiHoldings
  script: /holdings/getHathiHoldings.php

- url: /holdings/getIAHoldings
  script: /holdings/getIAHoldings.php

- url: /holdings/getMemberSpreadsheet
  script: /holdings/getMemberSpreadsheet.php

- url: /holdings/getMemberSpreadsheetDist
  script: /holdings/getMemberSpreadsheet.dist.php

- url: /holdings/getMemberSpreadsheetLive
  script: /holdings/getMemberSpreadsheet.live.php

# live holdings - using same as testing for now
#- url: /oclc
#  script: /testing/holdings/holdings.html

#- url: /holdings/searchresults
#  script: /testing/holdings/searchresults.html

#- url: /holdings/getOCLCHoldings
#  script: /testing/holdings/getOCLCHoldings.php

######  TESTING CRUD
- url: /testing/edit
  script: /testing/edit/index.php
  login: required

- url: /testing/edit/nologin
  script: /testing/edit/nologin.html

- url: /testing/edit/updates
  script: /testing/edit/searchRemove.html

- url: /testing/edit/resultsblock
  script: /testing/edit/eresultsblock.php

- url: /testing/edit/updateRetention
  script: /testing/edit/updateRetention.html

- url: /testing/twig
  script: /testing/twig.php5



# default url
#- url: /.*
#  script: helloworld.php

#application default page
- url: /.*
  script: home.html
